# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miPrimerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("documento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Botón para separar palabras
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 50, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Separar palabras")
        self.pushButton.clicked.connect(self.separar_p)
        
        # Botón para voltear palabras
        self.pushButtonInvertir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInvertir.setGeometry(QtCore.QRect(350, 90, 111, 25))
        self.pushButtonInvertir.setObjectName("pushButtonInvertir")
        self.pushButtonInvertir.setText("Voltear palabras")
        self.pushButtonInvertir.clicked.connect(self.voltear_palabras)
        
        # Tabla para mostrar palabras separadas
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 320, 731, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeaderLabels(['Palabras', 'Palabras Invertidas'])
        self.tableWidget.setColumnWidth(1, 150) 
        
        # TextEdit para entrada de texto
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 50, 250, 200))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(510, 50, 250, 200))
        self.textEdit_2.setObjectName("textEdit_2")
        
        # QLabel para mostrar el conteo de palabras
        self.label_count = QtWidgets.QLabel(self.centralwidget)
        self.label_count.setGeometry(QtCore.QRect(30, 260, 250, 25))
        self.label_count.setObjectName("label_count")
        self.label_count.setText("Cantidad de palabras: 0")

        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def separar_p(self):
        texto = self.textEdit.toPlainText()
        self.textEdit_2.setPlainText(texto)
        texto_spliteado = texto.split()
        
        # Actualizar el contador de palabras
        self.label_count.setText(f"Cantidad de palabras: {len(texto_spliteado)}")
        
        # Limpiar el contenido previo de la tabla
        self.tableWidget.setRowCount(0)
        
        # Insertar palabras en la primera columna de la tabla
        for i, palabra in enumerate(texto_spliteado):
            self.tableWidget.insertRow(i)
            self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(palabra))

    def voltear_palabras(self):
        # Verificar si hay palabras en la primera columna
        if self.tableWidget.rowCount() == 0:
            # Mostrar mensaje de advertencia en caso de que no estén separadas las palabras
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setWindowTitle("Advertencia")
            msg.setText("Primero debe dar clic en 'Separar palabras'")
            msg.exec_()
            return
        
        # Voltear las palabras que ya están en la primera columna
        rowCount = self.tableWidget.rowCount()
        
        for i in range(rowCount):
            palabra = self.tableWidget.item(i, 0).text()
            palabra_invertida = palabra[::-1]  # Invertir la palabra
            self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(palabra_invertida))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())